export const GET_PRODUCTS_DATA = 'GET_PRODUCTS_DATA';
export const SAVE_CART_FROM_LS = 'SAVE_CART_FROM_LS';
export const TOGGLE_IS_FAVOURITE_CARDS = 'TOGGLE_IS_FAVOURITE_CARDS';
export const SET_IS_OPEN_MODAL = 'SET_IS_OPEN_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';